language: node_js
node_js:
  - "8"
dist: xenial
sudo: false
branches:
  only:
    - master
    - "ANSSR-4"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - npm install -g @angular/cli
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run $COMMAND
      name: Test
      env: COMMAND="test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox"
    - script: npm run $COMMAND
      name: Lint
      install: skip
      env: COMMAND=lint
    - stage: build
      script:
        - ng build $BUILD
        # - mv dist/browser/index.html dist/browser/404.html
      name: Build
      env: BUILD="--prod --base-href /angular-ssr/"
      deploy:
        provider: heroku
        api_key:
          secure: tO7QvcsyO86x0DCHj/YhCSIYjdMbIoMotfmC/d8r0c+bfJE7kGl/k2nNbN4aYmSSzuP1zKnJQyKkireYKlP5BH8PgUbIvsYtFhZO2R7WLoAQmx8kn2p/Aojh+Zx03JFPawThl56x1LSZ6+rp2TKpdZDAnJBJs+ZEYOWoKk+7u6xRrabfk6MplMq/DZO51STdSjVF0w+JZ50/oOfBfiT94RUFcUwydL0iRoUB6bastG5U2YytBGQIwRI71Xiem/1MtLAUg0/1MxgPpNuN/Yd364maEVu5ofV7YLieZYWVEEd/nNC/3nQoNnri+fdAN5Bssfnc7Xit/gNBM8vV8kfAGEQwoPdYoLmeI3rCgqRR7AmpP4TgQiaFNGOcSOZDlh22rcCJFzjrK94zZakQR+jvFGl+geuqKMIOVN6CpLxkDo/5YgL7uEoPJaq1YEegVSSMxrc/3LT/vhkwrmIibN6JkrOzOixsAnRz14iw+ebL3tY9OdW7JRuL5vK4SxEAD9rX3TpzeYAvpNvYT6z+2ADzgSivF6rzlQOQjyW3xM+a6c3NkzHaR+5vtX421KA5QmDlNb5BZEW6PtPrp7EqqOWUtYeXhUNFz07CkEjWecdzYY49S5jStiC/AUthgznq25JJZpPAZqUIs7+osyclg0gEP/Sa9dosugoXRpCPYxzU06s=
        app: angular-ssr-1
        on:
          # branch: master
          all-branch: true
          condition: "$TRAVIS_BRANCH =~ ^master|ANSSR-4$"
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: ItSUhrYvq48iQOCCCD5sQSgv6y1rrbG1VyfmYfVYIlvfTnfzjoQC4Ob5YLe7FcxNDIWY3LOb0lQoF5tWG8eq61tol9BlbM0jlJeQimRKFIoPIZYsnhFFo9JgRqWI1TPmcUaHNmZ+4vs4EBAliCr7DqTvKXdJwqCrOFPG73ilMlyzpkfVO4VxUjCPaFq0ZGQ4G1zBKKp3nYjoMmuNCJy9R83PUAMwVwo2L8xg4oV7pY+Ky/Wh8dmz766/mxdRaWQNLFGP9RnGFYpC5VYdqW2WLh31BWsZcFczTfQ/RQp+QVi9sdzHWMThstRf2pYB3EgVD/dKm8CIZS8egy0DquDXpT5bsh4pzA3aQyr/r2c9v1Q7eBtuXty6Yb42U/oYPwaGVvgsjzl00Y+WahQ51yBdJ14QY0UKIB4S9Q5Nn+mVumQPmb0h7Gskg3NeIic210iKmd6ltpLwhSFpDKovF/ZzshfirRKyYmNvx4FjGWDIl+TE+54mX3H6wKgBMoW5b4UxsNcNWtsyF8fB6rBrP8y0kEBKunGMSlnM2pJSGnxx4Y2XMwMflEbtVXXuZ2jp/bwxaET4jeu2JdVnnSNcKz/V9/K+6hHsva1X4o8RwUGKpO45SVyaKyfeVWSSkCWKC/ZftvSQnp06jk3vvZSNZWTSZrXP99d9dsibv/plqE8drmg=
    on_success: always
    on_failure: always
    on_start: always
    template:
      - Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
        for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
